pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG = "${WORKSPACE}/deploy/.ansible.cfg"
    }

    stages {
        stage('Clean Up') {
            steps {
                cleanWs()
            }
        }

        // stage('Pull Code') {
        //     steps {
        //         // Correctly pulling the code from GitHub
        //         git branch: 'main', credentialsId: 'git', url: 'https://github.com/saurabhshende13/CI-CD-Pipeline-for-Java-Applications-Jenkins-Terraform-Ansible-SonarQube-JFrog-and-Tomcat.git'
        //     }
        // }

        stage('Execute Ansible') {
            steps {
                ansiblePlaybook(
                    credentialsId: 'ansible',
                    installation: 'ansible',
                    disableHostKeyChecking: true,
                    inventory: 'inventory/dev.ini',
                    playbook: 'playbooks/site.yml'
                )
            }
        }
    }
}
